# Generated by Django 4.2.6 on 2023-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.TextField()),
                ("lookup_identifier", models.TextField()),
                ("unit", models.CharField(max_length=100)),
                ("co2e_factor", models.FloatField()),
                ("scope", models.IntegerField()),
                ("category", models.IntegerField(default=None, null=True)),
            ],
            options={
                "unique_together": {("activity", "lookup_identifier")},
                "index_together": {("activity", "lookup_identifier")},
            },
        ),
        migrations.CreateModel(
            name="Emmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co2e", models.FloatField(db_index=True)),
                ("scope", models.IntegerField(db_index=True)),
                (
                    "category",
                    models.IntegerField(db_index=True, default=None, null=True),
                ),
                ("activity", models.TextField()),
            ],
            options={
                "index_together": {("scope", "category", "co2e")},
            },
        ),
    ]
